version: "3.7"
services:
  profile-api:
    build: profile-api
    restart: always
    ports:
      - ${API_PORT}:8080
    links:
      - mongo_db:profile-api-db
    depends_on:
      - mongo_db
    environment:
      - SERVER_PORT=8080
      - SPRING_DATA_MONGODB_HOST=mongo_db
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=${MONGO_INIT_DB}
      - JWT_COOKIE_NAME=token
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS}
      - JWT_REFRESH_EXPIRATION_MS=${JWT_REFRESH_EXPIRATION_MS}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    networks:
      - main-back-end
  mongo_db:
    image: "mongo:latest"
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INIT_DB}
    networks:
      - main-back-end
networks:
  main-back-end:
    name: ${NETWORK_NAME}