on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  notify:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Trigger HTTP Request
        run: |
          curl -X POST https://ci.hjusic.com/job/profile-cms/build?token=profileCmsBuildNow
