on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  notify:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
      JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
    steps:
      - name: Trigger HTTP Request
        run: |
          curl -X GET -u $JENKINS_USERNAME:$JENKINS_API_TOKEN https://ci.hjusic.com/job/profile-cms/build?token=profilecmsbuildnow

